### ISSUE TITLE
Find the source of those source of `.unknown` & `.internal` errors

### ISSUE THREAD

**Issue by duyhungtnn** [bucketeer-io/ios-client-sdk#64]
There are some records about `unknown` & `internal` tracked.
We need to find the source of `.unknown` & `.internal` errors

### Targets
- To know if it's a problem with the server response or something wrong with the client
- if the client SDK is tracking an invalid event, we must fix it. 

### TODO

- [x] iOS
- [ ] Android
- [ ] JavaScript

**Comment by cre8ivejp** [comment]
iOS done.
https://github.com/bucketeer-io/ios-client-sdk/issues/65

**Comment by cre8ivejp** [comment]
Closing this because we will manage the other SDK changes in their repositories.

https://github.com/bucketeer-io/javascript-client-sdk/issues/131
https://github.com/bucketeer-io/android-client-sdk/issues/136
