### ISSUE TITLE
chore: update errors metrics report

### ISSUE THREAD

**Issue by duyhungtnn** [bucketeer-io/ios-client-sdk#65]
# TODO
- Track the 3xx status code as "RedirectRequestException". 
    - add `response_code` via labels
- Track the 413 status code as "PayloadTooLargeException"
- 408 errors, and we should handle it as a timeout error.
- Make iOS error handling consistent with Android SDK. Android handles more error code than iOS SDK. That is  ( 405, 502, 504)
-  Implement adding more information via labels for Unknown errors, so we don't spend too much time debugging.
    -  Add `error_message` and `response_code` to the ErrorMetricsEvent labels 

### Note 
the current metrics on the server are the following.
https://github.com/bucketeer-io/bucketeer/blob/main/proto/event/client/event.proto#L99-L187

**Comment by cre8ivejp** [comment]
Done.
